
name: Actualizar datos de humedad

on:
  schedule:
    - cron: '0 0 * * *'  # Ejecutar todos los días a medianoche UTC
  workflow_dispatch:  # Permite ejecutarlo manualmente

jobs:
  actualizar-datos:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install requests

      - name: Descargar datos MQTT (simulado)
        run: python actualizar_datos.py  # Script para obtener datos nuevos

      - name: Confirmar y subir cambios
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add datos.json
          git commit -m "📊 Actualización diaria de datos.json"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
